import { useMemo } from "react";
import { useFleetStore } from "../stores/fleet";
import { usePlanStore } from "../stores/plan";
import { useConfigStore } from "../stores/config";
import { useWebSocket } from "../hooks/useWebSocket";
import { postKill } from "../api";
import { RobotCard } from "../components/RobotCard";
import { YardMap } from "../components/YardMap";
import { EventLog } from "../components/EventLog";
import { colors } from "../theme";

const COLORS = ["#03045e", "#023e8a", "#0077b6", "#0096c7", "#03045e", "#023e8a"];

/**
 * View 4: Live Mission Dashboard
 * Light theme — clean white cards, subtle borders, blue accents.
 * 
 * NO static/fake robot data is ever shown. Robot cards only appear
 * when real telemetry arrives via WebSocket. The YardMap only shows
 * locations from the real DAG (generated by LLM).
 */
export function DashboardView() {
  const robots = useFleetStore((s) => s.robots);
  const tasksCompleted = useFleetStore((s) => s.tasksCompleted);
  const tasksTotal = useFleetStore((s) => s.tasksTotal);
  const missionTime = useFleetStore((s) => s.missionTime);
  const connected = useFleetStore((s) => s.connected);
  const phase = usePlanStore((s) => s.phase);
  const currentDag = usePlanStore((s) => s.currentDag);
  const resetPlan = usePlanStore((s) => s.reset);
  const resetFleet = useFleetStore((s) => s.reset);
  const sessionId = useConfigStore((s) => s.sessionId);
  const robotCount = useConfigStore((s) => s.robotCount);
  const mockMode = useConfigStore((s) => s.mockMode);

  useWebSocket();

  const hasRobots = robots.length > 0;
  const hasRealDag = currentDag !== null && currentDag?.locations != null && Object.keys(currentDag.locations).length > 0;

  const logEntries = useMemo(() => {
    const e: Array<{ timestamp: string; type: "TASK" | "BATTERY" | "MISSION" | "ERROR"; message: string }> = [];
    const t = (s: number) => `${String(Math.floor(s/60)).padStart(2,"0")}:${String(Math.floor(s%60)).padStart(2,"0")}:01`;
    for (const r of robots) {
      if (r.current_task) e.push({ timestamp: t(missionTime), type: "TASK", message: `${r.id} ${r.current_task}` });
      if (r.battery < 20) e.push({ timestamp: t(missionTime), type: "BATTERY", message: `${r.id} low battery (${Math.round(r.battery)}%)` });
    }
    if (phase === "complete") e.push({ timestamp: t(missionTime), type: "MISSION", message: `All ${tasksTotal} tasks done at ${missionTime.toFixed(1)}s` });
    return e;
  }, [robots, phase, missionTime, tasksTotal]);

  const isComplete = phase === "complete";

  return (
    <div style={styles.container}>
      {isComplete && (
        <div style={styles.completeBanner}>
          MISSION COMPLETE — {tasksCompleted}/{tasksTotal} tasks in {missionTime.toFixed(1)}s
        </div>
      )}

      {/* Robot cards — only shown when real telemetry arrives */}
      <div style={styles.cardsSection}>
        {hasRobots ? (
          <div style={styles.cardsRow}>
            {robots.map((r, i) => (
              <RobotCard key={r.id} robot={r as any} color={COLORS[i % COLORS.length]} />
            ))}
          </div>
        ) : (
          <div style={styles.waitingRobots}>
            <div style={styles.waitingPulse} />
            <span style={styles.waitingText}>
              {mockMode
                ? "MOCK MODE — No robot telemetry. Connect ANTHROPIC_API_KEY and launch a real mission."
                : `Waiting for telemetry from ${robotCount} robot${robotCount > 1 ? 's' : ''}...`}
            </span>
          </div>
        )}
      </div>

      {/* Middle: Summary + Map */}
      <div style={styles.middle}>
        <div style={styles.summary}>
          <SummaryRow label="Tasks" value={hasRobots ? `${tasksCompleted} / ${tasksTotal}` : "—"} />
          <SummaryRow label="Time" value={hasRobots ? `${missionTime.toFixed(1)}s` : "—"} />
          <SummaryRow label="Active" value={hasRobots ? `${robots.filter(r=>r.status!=="idle").length} / ${robots.length}` : "—"} />
          <SummaryRow label="Status" value={connected ? "Connected" : "Disconnected"}
            valueColor={connected ? colors.status.connected : colors.status.disconnected} />
        </div>
        {hasRealDag ? (
          <YardMap robots={robots} dag={currentDag} planned={false} />
        ) : (
          <div style={styles.emptyMap}>
            <svg width="40" height="40" viewBox="0 0 40 40" fill="none">
              <rect x="5" y="10" width="30" height="18" rx="3" fill={colors.border.default} />
              <circle cx="15" cy="22" r="4" fill={colors.border.default} />
              <circle cx="25" cy="22" r="4" fill={colors.border.default} />
            </svg>
            <div style={styles.emptyMapText}>
              {mockMode
                ? "MOCK MODE — No mission DAG loaded."
                : "Waiting for mission DAG..."}
            </div>
          </div>
        )}
      </div>

      {/* Log */}
      <div style={styles.logSection}>
        <EventLog entries={logEntries} />
      </div>

      {isComplete && (
        <div style={styles.newMissionArea}>
          <button style={styles.newBtn} onClick={async () => {
            await postKill(sessionId); resetPlan(); resetFleet();
          }}>
            Start New Mission
          </button>
        </div>
      )}
    </div>
  );
}

function SummaryRow({ label, value, valueColor }: { label: string; value: string; valueColor?: string }) {
  return (
    <div style={styles.summaryRow}>
      <span style={styles.summaryLabel}>{label}</span>
      <span style={{ ...styles.summaryValue, ...(valueColor ? { color: valueColor } : {}) }}>{value}</span>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", background: colors.surface.subtle, position: "relative" },
  completeBanner: { background: colors.success, color: colors.primaryForeground, textAlign: "center", padding: "10px 16px", fontSize: 15, fontWeight: 700 },
  cardsSection: { padding: "12px 16px", borderBottom: `1px solid ${colors.border.default}`, overflowX: "auto", background: colors.surface.default },
  cardsRow: { display: "flex", gap: 10 },
  waitingRobots: { display: "flex", alignItems: "center", gap: 12, justifyContent: "center", padding: "16px 0" },
  waitingPulse: { width: 10, height: 10, borderRadius: "50%", background: colors.border.default, animation: "pulse 2s infinite" },
  waitingText: { color: colors.text.faint, fontSize: 13, fontStyle: "italic" },
  middle: { flex: 1, display: "flex", overflow: "hidden" },
  summary: {
    width: 180, minWidth: 180, padding: 16, display: "flex", flexDirection: "column", gap: 12,
    background: colors.surface.default, borderRight: `1px solid ${colors.border.default}`,
  },
  summaryRow: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  summaryLabel: { color: colors.text.muted, fontSize: 12 },
  summaryValue: { color: colors.text.primary, fontSize: 13, fontWeight: 600 },
  emptyMap: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 10, background: colors.surface.subtle },
  emptyMapText: { color: colors.text.faint, fontSize: 13, fontStyle: "italic" },
  logSection: { height: 180, minHeight: 180, borderTop: `1px solid ${colors.border.default}`, padding: "8px 16px", background: colors.surface.default },
  newMissionArea: { position: "absolute", bottom: 200, left: "50%", transform: "translateX(-50%)" },
  newBtn: { background: colors.primary, color: colors.primaryForeground, border: "none", borderRadius: 8, padding: "12px 24px", fontSize: 14, fontWeight: 700, cursor: "pointer", boxShadow: `0 2px 8px ${colors.primary}40` },
};
